name: dartdeps

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.0
  io: ^0.3.3
  stream_transform: ^1.0.0
  path: ^1.6.0
  yaml: ^2.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.3.0
